package com.kwad.sdk.core.b.a;

import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.a.a;
import com.kwad.components.core.webview.jshandler.a.e;
import com.kwad.components.core.webview.jshandler.a.f;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ap;
import com.kwad.components.core.webview.jshandler.aq;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.aw;
import com.kwad.components.core.webview.jshandler.az;
import com.kwad.components.core.webview.jshandler.bb;
import com.kwad.components.core.webview.jshandler.bf;
import com.kwad.components.core.webview.jshandler.bh;
import com.kwad.components.core.webview.jshandler.bj;
import com.kwad.components.core.webview.jshandler.bm;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.tachikoma.b.h;
import com.kwad.components.core.webview.tachikoma.b.u;
import com.kwad.components.core.webview.tachikoma.b.x;
import com.kwad.sdk.j.a;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* loaded from: D:\123Browser\下载\dump_dex_com.awfgwfd.joiyuevgyftrsa\class6.dex */
public final class dg {
    public static void aab() {
        hr.aac().put(j.a.class, new ga());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cq());
        hr.aac().put(u.b.class, new ma());
        hr.aac().put(UaidInfo.class, new ni());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.o.class, new ji());
        hr.aac().put(a.b.class, new ld());
        hr.aac().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ab());
        hr.aac().put(aq.b.class, new hn());
        hr.aac().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ht());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.u.class, new lm());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.p.class, new jn());
        hr.aac().put(com.kwad.sdk.a.a.a.a.class, new hc());
        hr.aac().put(com.kwad.components.core.webview.a.b.class, new jh());
        hr.aac().put(e.a.class, new le());
        hr.aac().put(KGeoInfo.class, new hs());
        hr.aac().put(ap.b.class, new gg());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.w.class, new nm());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.i.class, new fi());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.e.class, new cf());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.r.class, new li());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.v.class, new lz());
        hr.aac().put(d.a.class, new ns());
        hr.aac().put(l.a.class, new gc());
        hr.aac().put(WebCardVideoPositionHandler.VideoPosition.class, new nx());
        hr.aac().put(g.a.class, new fx());
        hr.aac().put(bj.a.class, new gl());
        hr.aac().put(ah.a.class, new kc());
        hr.aac().put(com.kwad.components.core.webview.a.c.class, new jj());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.x.class, new nq());
        hr.aac().put(bm.a.class, new hq());
        hr.aac().put(a.C0617a.class, new lc());
        hr.aac().put(com.kwad.components.core.p.c.b.class, new jg());
        hr.aac().put(av.b.class, new bk());
        hr.aac().put(ak.a.class, new nn());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.t.class, new ll());
        hr.aac().put(d.b.class, new nt());
        hr.aac().put(av.a.class, new bj());
        hr.aac().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ac());
        hr.aac().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ad());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.g.class, new ct());
        hr.aac().put(y.a.class, new w());
        hr.aac().put(h.a.class, new fy());
        hr.aac().put(ao.a.class, new dq());
        hr.aac().put(h.b.class, new kb());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.m.class, new hx());
        hr.aac().put(com.kwad.components.core.page.b.a.class, new hw());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bl());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.j.class, new gd());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.z.class, new ny());
        hr.aac().put(x.a.class, new bn());
        hr.aac().put(v.b.class, new mg());
        hr.aac().put(a.C0491a.class, new ck());
        hr.aac().put(a.b.class, new el());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.d.class, new bs());
        hr.aac().put(m.b.class, new hb());
        hr.aac().put(at.a.class, new jq());
        hr.aac().put(f.a.class, new cp());
        hr.aac().put(j.b.class, new gb());
        hr.aac().put(q.a.class, new in());
        hr.aac().put(bf.a.class, new nz());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.h.class, new eb());
        hr.aac().put(com.kwad.components.core.m.a.class, new u());
        hr.aac().put(bb.a.class, new ia());
        hr.aac().put(az.a.class, new od());
        hr.aac().put(com.kwad.components.core.p.c.d.class, new nl());
        hr.aac().put(u.a.class, new mk());
        hr.aac().put(i.a.class, new fz());
        hr.aac().put(au.a.class, new bg());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.q.class, new jz());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.s.class, new lk());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.n.class, new ip());
        hr.aac().put(a.c.class, new iy());
        hr.aac().put(m.a.class, new ha());
        hr.aac().put(bh.a.class, new mu());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.c.class, new bq());
        hr.aac().put(WarmUpReportMessage.class, new ob());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.k.class, new ho());
        hr.aac().put(f.a.class, new fw());
        hr.aac().put(aq.a.class, new hm());
        hr.aac().put(e.b.class, new gt());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        hr.aac().put(a.C0490a.class, new al());
        hr.aac().put(al.a.class, new gn());
        hr.aac().put(a.C0489a.class, new ei());
        hr.aac().put(com.kwad.components.core.webview.tachikoma.c.y.class, new nu());
        hr.aac().put(ai.a.class, new kd());
        hr.aac().put(com.kwad.components.core.video.a.e.class, new oc());
        hr.aac().put(aw.a.class, new bu());
    }
}
