package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.ForInvoker;
import com.kwad.sdk.commercial.j.a;
import com.kwad.sdk.commercial.model.HybridLoadMsg;
import com.kwad.sdk.commercial.model.SDKInitMsg;
import com.kwad.sdk.commercial.model.WebCloseStatus;
import com.kwad.sdk.commercial.model.WebViewCommercialMsg;
import com.kwad.sdk.commercial.model.WebViewLoadMsg;
import com.kwad.sdk.core.h.a;
import com.kwad.sdk.core.imageloader.ImageLoaderInfo;
import com.kwad.sdk.core.request.model.StatusInfo;
import com.kwad.sdk.core.response.model.ABParams;
import com.kwad.sdk.core.response.model.AdGlobalConfigInfo;
import com.kwad.sdk.core.response.model.AdInfo;
import com.kwad.sdk.core.response.model.AdMatrixInfo;
import com.kwad.sdk.core.response.model.AdProductInfo;
import com.kwad.sdk.core.response.model.AdStatusInfo;
import com.kwad.sdk.core.response.model.AdStyleInfo;
import com.kwad.sdk.core.response.model.AdTemplate;
import com.kwad.sdk.core.response.model.AdVideoPreCacheConfig;
import com.kwad.sdk.core.response.model.CouponInfo;
import com.kwad.sdk.core.response.model.FeedSlideConf;
import com.kwad.sdk.core.response.model.HttpDnsInfo;
import com.kwad.sdk.core.response.model.PageInfo;
import com.kwad.sdk.core.response.model.PhotoInfo;
import com.kwad.sdk.core.response.model.TKAdLiveShopItemInfo;
import com.kwad.sdk.core.response.model.TemplateConfig;
import com.kwad.sdk.core.response.model.VideoPlayerStatus;
import com.kwad.sdk.core.scene.URLPackage;
import com.kwad.sdk.internal.api.AdLabelImpl;
import com.kwad.sdk.internal.api.NativeAdExtraDataImpl;
import com.kwad.sdk.internal.api.SceneImpl;
import com.kwad.sdk.internal.api.SplashExtraDataImpl;
import com.kwad.sdk.p.l;
import java.util.HashMap;
import java.util.Map;

/* loaded from: D:\123Browser\下载\dump_dex_com.awfgwfd.joiyuevgyftrsa\class6.dex */
public final class hr {
    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aVl;

    static {
        HashMap map = new HashMap();
        aVl = map;
        map.put(AdStyleInfo.class, new at());
        aVl.put(AdInfo.AdConversionInfo.DeeplinkItemInfo.class, new ec());
        aVl.put(AdMatrixInfo.RewardWebTaskCloseInfo.class, new kx());
        aVl.put(AdInfo.ComplianceInfo.class, new cu());
        aVl.put(AdInfo.AdBaseInfo.class, new j());
        aVl.put(AdInfo.FullScreenVideoInfo.class, new fu());
        aVl.put(StatusInfo.NativeAdStyleControl.class, new iu());
        aVl.put(AdInfo.H5Config.class, new gf());
        aVl.put(com.kwad.sdk.core.report.j.class, new ey());
        aVl.put(AdMatrixInfo.PreLandingPageTKInfo.class, new kg());
        aVl.put(AdMatrixInfo.ComponentParam.class, new cv());
        aVl.put(AdStyleInfo.PlayDetailInfo.DetailCommonInfo.class, new ee());
        aVl.put(PhotoInfo.class, new jx());
        aVl.put(AdStyleInfo.PlayEndInfo.AdWebCardInfo.class, new ba());
        aVl.put(ImageLoaderInfo.class, new gw());
        aVl.put(AdInfo.AdPreloadInfo.class, new am());
        aVl.put(AdInfo.AdStyleConfInfo.class, new as());
        aVl.put(AdMatrixInfo.EndCardInfo.class, new ev());
        aVl.put(AdStyleInfo.PlayDetailInfo.ActionBarInfo.class, new c());
        aVl.put(AdMatrixInfo.TemplateData.class, new mx());
        aVl.put(AdVideoPreCacheConfig.class, new az());
        aVl.put(URLPackage.class, new nh());
        aVl.put(AdMatrixInfo.RotateDegreeInfo.class, new kz());
        aVl.put(AdMatrixInfo.AggregationCardInfo.class, new bc());
        aVl.put(com.kwad.sdk.commercial.j.b.class, new ay());
        aVl.put(AdInfo.class, new x());
        aVl.put(AdMatrixInfo.SlideInfo.class, new ln());
        aVl.put(AdStyleInfo.PlayDetailInfo.PatchEcInfo.class, new ju());
        aVl.put(a.C0574a.class, new nc());
        aVl.put(l.a.C0631a.class, new mf());
        aVl.put(PhotoInfo.VideoInfo.class, new nr());
        aVl.put(AdMatrixInfo.StyleInfo.class, new mm());
        aVl.put(VideoPlayerStatus.class, new nw());
        aVl.put(SDKInitMsg.class, new lb());
        aVl.put(AdStyleInfo.PlayDetailInfo.class, new jy());
        aVl.put(AdInfo.UnDownloadRegionConf.class, new nk());
        aVl.put(AdMatrixInfo.RewardVideoInteractInfo.class, new kv());
        aVl.put(com.kwad.sdk.commercial.e.c.class, new q());
        aVl.put(AdStyleInfo.PlayDetailInfo.PatchAdInfo.class, new jt());
        aVl.put(AdStyleInfo.ExtraDisplayInfo.class, new fd());
        aVl.put(AdTemplate.class, new av());
        aVl.put(AdMatrixInfo.MatrixTag.class, new ik());
        aVl.put(com.kwad.sdk.h.a.a.class, new jk());
        aVl.put(l.a.class, new oi());
        aVl.put(TemplateConfig.class, new mv());
        aVl.put(AdGlobalConfigInfo.CycleAggregationInfo.class, new ea());
        aVl.put(com.kwad.sdk.commercial.d.b.class, new n());
        aVl.put(AdInfo.AdTrackInfo.class, new aw());
        aVl.put(NativeAdExtraDataImpl.class, new iq());
        aVl.put(com.kwad.sdk.core.request.model.g.class, new np());
        aVl.put(AdMatrixInfo.RewardVideoTaskInfo.class, new kw());
        aVl.put(AdMatrixInfo.ShakeInfo.class, new lg());
        aVl.put(AdMatrixInfo.ComponentTemplateInfo.class, new cw());
        aVl.put(AdMatrixInfo.RotateInfo.class, new la());
        aVl.put(StatusInfo.NativeAdRequestInfo.class, new is());
        aVl.put(AdInfo.UnDownloadConf.class, new nj());
        aVl.put(AdInfo.AdMaterialInfo.class, new aj());
        aVl.put(AdMatrixInfo.AdDataV2.class, new r());
        aVl.put(AdInfo.AdFeedInfo.class, new t());
        aVl.put(PageInfo.class, new jo());
        aVl.put(AdMatrixInfo.SplashSlideInfo.class, new mc());
        aVl.put(AdInfo.DownloadSafeInfo.class, new ek());
        aVl.put(AdStyleInfo.ExposeTagInfo.class, new fb());
        aVl.put(AdInfo.SmallAppJumpInfo.class, new lo());
        aVl.put(AdMatrixInfo.BottomBannerInfo.class, new ce());
        aVl.put(com.kwad.sdk.core.threads.d.class, new mz());
        aVl.put(AdMatrixInfo.DownloadTexts.class, new em());
        aVl.put(com.kwad.sdk.core.request.model.d.class, new jc());
        aVl.put(HttpDnsInfo.class, new gr());
        aVl.put(AdInfo.MaterialSize.class, new ij());
        aVl.put(AdMatrixInfo.SplashInfo.class, new lv());
        aVl.put(AdMatrixInfo.FeedInfo.class, new fh());
        aVl.put(TKAdLiveShopItemInfo.class, new mo());
        aVl.put(HybridLoadMsg.class, new gs());
        aVl.put(AdProductInfo.class, new an());
        aVl.put(StatusInfo.class, new mj());
        aVl.put(AdGlobalConfigInfo.NeoScanAggregationSceneInfo.class, new iz());
        aVl.put(com.kwad.sdk.core.request.model.f.class, new mt());
        aVl.put(AdStatusInfo.class, new ar());
        aVl.put(AdInfo.RewardFraudVerifyInfo.class, new kr());
        aVl.put(AdMatrixInfo.Styles.class, new mn());
        aVl.put(AdStyleInfo.AdBrowseInfo.class, new l());
        aVl.put(AdInfo.AdBannerInfo.class, new i());
        aVl.put(FeedSlideConf.class, new fk());
        aVl.put(AdMatrixInfo.MatrixTemplate.class, new il());
        aVl.put(SplashExtraDataImpl.class, new lu());
        aVl.put(AdInfo.AdSplashInfo.class, new aq());
        aVl.put(AdMatrixInfo.NativeMatrixAdInfo.class, new iw());
        aVl.put(AdMatrixInfo.MerchantLiveReservationInfo.LiveReservationPlayEndInfo.class, new hz());
        aVl.put(com.kwad.sdk.core.network.i.class, new jd());
        aVl.put(ABParams.class, new a());
        aVl.put(AdInfo.AdShowVideoH5Info.class, new ap());
        aVl.put(AdMatrixInfo.SplashActionBarInfo.class, new lr());
        aVl.put(com.kwad.sdk.commercial.a.b.class, new bi());
        aVl.put(AdInfo.AdAggregateInfo.class, new h());
        aVl.put(AdMatrixInfo.InstalledActivateInfo.class, new hd());
        aVl.put(AdInfo.AdLiveTypeInfo.class, new ae());
        aVl.put(SceneImpl.class, new lf());
        aVl.put(AdInfo.AdvertiserInfo.class, new bb());
        aVl.put(AdMatrixInfo.BaseMatrixTemplate.class, new ca());
        aVl.put(AdStyleInfo.PlayDetailInfo.DetailTopToolBarInfo.class, new ef());
        aVl.put(AdStyleInfo.PlayEndInfo.EndTopToolBarInfo.class, new ew());
        aVl.put(AdMatrixInfo.class, new ak());
        aVl.put(com.kwad.sdk.commercial.c.a.class, new bz());
        aVl.put(AdMatrixInfo.InterstitialCardInfo.class, new hh());
        aVl.put(StatusInfo.SplashAdInfo.class, new ls());
        aVl.put(AdProductInfo.SpikeInfo.class, new lq());
        aVl.put(AdInfo.AdMaterialInfo.MaterialFeature.class, new ih());
        aVl.put(AdMatrixInfo.AdInteractionInfo.class, new z());
        aVl.put(AdMatrixInfo.SplashEndCardTKInfo.class, new lt());
        aVl.put(AdMatrixInfo.StyleComponentInfo.class, new ml());
        aVl.put(com.kwad.sdk.core.threads.b.class, new my());
        aVl.put(AdInfo.CutRuleInfo.class, new dy());
        aVl.put(AdMatrixInfo.MerchantLiveReservationInfo.class, new im());
        aVl.put(AdStyleInfo.PlayDetailInfo.WidgetAdInfo.class, new oh());
        aVl.put(AdStyleInfo.PlayEndInfo.class, new ka());
        aVl.put(HttpDnsInfo.IpInfo.class, new hl());
        aVl.put(com.kwad.sdk.commercial.b.b.class, new bm());
        aVl.put(AdInfo.AdInsertScreenInfo.class, new y());
        aVl.put(AdStyleInfo.FeedAdInfo.class, new ff());
        aVl.put(com.kwad.sdk.commercial.i.a.class, new Cif());
        aVl.put(AdInfo.AdDrawInfo.class, new s());
        aVl.put(AdInfo.AdConversionInfo.class, new m());
        aVl.put(AdStyleInfo.PlayDetailInfo.DrawAdInfo.class, new en());
        aVl.put(a.C0588a.class, new mq());
        aVl.put(PhotoInfo.BaseInfo.class, new by());
        aVl.put(com.kwad.sdk.core.request.model.b.class, new eh());
        aVl.put(WebCloseStatus.class, new oe());
        aVl.put(com.kwad.sdk.commercial.f.b.class, new ed());
        aVl.put(com.kwad.sdk.commercial.smallApp.b.class, new lp());
        aVl.put(AdGlobalConfigInfo.class, new v());
        aVl.put(AdMatrixInfo.NeoVideoInfo.class, new jb());
        aVl.put(com.kwad.sdk.core.config.d.class, new jm());
        aVl.put(AdMatrixInfo.CycleAggregateInfo.class, new dz());
        aVl.put(AdMatrixInfo.SplashPlayCardTKInfo.class, new ly());
        aVl.put(AdStyleInfo.PlayDetailInfo.DetailWebCardInfo.class, new eg());
        aVl.put(AdMatrixInfo.FullScreenInfo.class, new ft());
        aVl.put(CouponInfo.class, new dm());
        aVl.put(AdLabelImpl.class, new aa());
        aVl.put(com.kwad.sdk.h.a.b.class, new jl());
        aVl.put(AdMatrixInfo.ActionBarInfoNew.class, new d());
        aVl.put(WebViewCommercialMsg.class, new of());
        aVl.put(AdMatrixInfo.ActivityMiddlePageInfo.class, new g());
        aVl.put(AdInfo.PlayableStyleInfo.class, new ke());
        aVl.put(StatusInfo.SplashStyleControl.class, new md());
        aVl.put(AdInfo.NativeAdShakeInfo.class, new it());
        aVl.put(com.kwad.sdk.core.network.j.class, new je());
        aVl.put(AdInfo.NativeAdInfo.class, new ir());
        aVl.put(com.kwad.sdk.commercial.g.b.class, new gi());
        aVl.put(WebViewLoadMsg.class, new og());
        aVl.put(com.kwad.sdk.commercial.e.b.class, new p());
        aVl.put(AdInfo.AdRewardInfo.class, new ao());
        aVl.put(com.kwad.sdk.utils.b.a.class, new hv());
        aVl.put(AdMatrixInfo.DynamicAdStyleInfo.class, new eq());
        aVl.put(AdInfo.CallBackStrategyInfo.class, new ci());
        aab();
    }

    @ForInvoker(methodId = "registerHolder")
    private static void aab() {
        cx.aab();
        cy.aab();
        cz.aab();
        da.aab();
        db.aab();
        dc.aab();
        dd.aab();
        de.aab();
        df.aab();
        dg.aab();
        dh.aab();
        di.aab();
        dj.aab();
        dk.aab();
        fm.aab();
        fn.aab();
        fo.aab();
        fp.aab();
        fq.aab();
        fr.aab();
    }

    public static Map<Class<? extends com.kwad.sdk.core.response.a.a>, com.kwad.sdk.core.d> aac() {
        return aVl;
    }

    public static com.kwad.sdk.core.d getHolder(Class<? extends com.kwad.sdk.core.response.a.a> cls) {
        return aVl.get(cls);
    }
}
