package com.tkruntime.v8;

import androidx.constraintlayout.core.motion.utils.TypedValues;
import com.baidu.mobads.container.n.f;
import com.baidu.mobads.container.util.animation.j;
import com.luck.picture.lib.config.CustomIntentKey;
import com.sigmob.sdk.base.mta.PointCategory;

/* loaded from: D:\123Browser\下载\dump_dex_com.awfgwfd.joiyuevgyftrsa\class16.dex */
public class StringPool {
    public static final String[] sSortedHighFrequencyStrings = {"100%", "absolute", "alignContent", "alignItems", "alignSelf", CustomIntentKey.EXTRA_ASPECT_RATIO, "auto", f.T, "backgroundImage", "baseline", "borderAll", "borderBottom", "borderColor", "borderEnd", "borderHorizontal", "borderLeft", "borderRadius", "borderRight", "borderStart", "borderStyle", "borderTop", "borderVertical", "borderWidth", j.g, "bottomLeftRadius", "bottomRightRadius", "center", TypedValues.Custom.S_COLOR, "column", "column-reverse", "cornerRadius", "cursorColor", "direction", "display", PointCategory.END, "flex", "flex-end", "flex-start", "flexBasis", "flexDirection", "flexGrow", "flexShrink", "flexWrap", "fontFamily", "fontSize", "fontWeight", "gradientBgColor", "gradientTextColor", "height", "hidden", "includeFontPadding", "indeterminate", "inherit", "justifyContent", j.d, "lineHeight", "margin", "marginAll", "marginBottom", "marginEnd", "marginHorizontal", "marginLeft", "marginRight", "marginStart", "marginTop", "marginVertical", "maxHeight", "maxLength", "maxWidth", "minHeight", "minWidth", "minimumTextScaleFactor", "none", "nowrap", "offColor", "onColor", "opacity", "overflow", "padding", "paddingAll", "paddingBottom", "paddingEnd", "paddingHorizontal", "paddingLeft", "paddingRight", "paddingStart", "paddingTop", "paddingVertical", "placeholderColor", "placeholderFontSize", "position", "positionAll", "positionBottom", "positionEnd", "positionHorizontal", "positionLeft", "positionRight", "positionStart", "positionTop", "positionType", "positionVertical", "relative", "resize", "returnKeyType", j.e, "row", "row-reverse", "scroll", "shadow", "space-around", "space-between", "space-evenly", "start", "static", "stretch", "textAlign", "textDecoration", "textDecorationLine", "textLineClamp", "textLineHeight", "textLineSpace", "textOverflow", "thumbColor", j.f, "topLeftRadius", "topRightRadius", "type", "visibility", "visible", "width", "wrap", "wrap-reverse", "transform", j.a, "scale", "rotate", "x", "y", "z", "backgroundSize", "borderLeftWidth", "borderTopWidth", "borderRightWidth", "borderBottomWidth", "borderLeftColor", "borderTopColor", "borderRightColor", "borderBottomColor", "lineClamp", "textVerticalAlign", "fontStyle", "textLineHeightClamp", "textLetterSpace", "letterSpacing", "textShadow"};
}
