package com.kwad.sdk.core.config;

import com.baidu.mobstat.forbes.Config;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import java.util.ArrayList;

/* loaded from: D:\123Browser\下载\dump_dex_com.awfgwfd.joiyuevgyftrsa\class6.dex */
public final class c {
    public static final com.kwad.sdk.core.config.item.d bwQ = new com.kwad.sdk.core.config.item.d("tkRenderTypeSwitch", false);
    public static final o bwR = new o("feedTKIdleTime", 0L);
    public static k bwS = new k("batchReportCatchLimit", 20);
    public static k bwT = new k("exceptionCollectorSwitch", 1);
    public static k bwU = new k("catchExceptionReportSwitch", 1);
    public static k bwV = new k("mediaPlayerLogReport", 0);
    public static k bwW = new k("didCopySwitch", 1);
    public static k bwX = new k("enableHodor", 0);
    public static k bwY = new k("speedLimitSwitch", 1);
    public static k bwZ = new k("speedLimitThreshold", 200);
    public static k bxa = new k("ksNativeAdCustomSwitch", 0);
    public static k bxb = new k("compoAndSoThreadPoolCoreSize", 0);
    public static k bxc = new k("forceActivateAfterInstalled", 0);
    public static k bxd = new k("spliceVideoInteractionType", 0);
    public static k bxe = new k("feedLoadOptimizeType", 0);
    public static k bxf = new k("feedLoadOptimizeExternalEnable", 0);
    public static k bxg = new k("nativeAdSlideClickDisable", 0);
    public static r bxh = new r("uaid", "");
    public static o bxi = new o("uaidExpireSec", 0L);
    public static o bxj = new o("uaidRequestDelayTime", 5L);
    public static k bxk = new k("interstitialAdLoadProcessChange", 0);
    public static k bxl = new k("interstitialAdActivityOpt", 0);
    public static k bxm = new k("formAdExitInterceptSwitch", 0);
    public static k bxn = new k("adLeaveConfirmSwitch", 0);
    public static k bxo = new k("viewLandingPageTaskDuration", 15);
    public static k bxp = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d bxq = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static o bxr = new o("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d bxs = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d bxt = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d bxu = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static k bxv = new k("commercialLoggerSwitch", 1);
    public static r bxw = new r("tkSoUrlV7a", "");
    public static r bxx = new r("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d bxy = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static m bxz = new m("playerConfig", null);
    public static s bxA = new s("pkgNameList", new ArrayList(0));
    public static s bxB = new s("hostList", new ArrayList(0));
    public static s bxC = new s("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem bxD = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c bxE = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem bxF = new InstallActivateReminderConfigItem();
    public static com.kwad.sdk.core.config.item.e bxG = new com.kwad.sdk.core.config.item.e();
    public static l<Integer> bxH = new l<>("adTKGrayConfig");
    public static p bxI = new p("realtimeReportActions", "");
    public static q bxJ = new q();
    public static k bxK = new k("appInstallNoticeSecond", 0);
    public static k bxL = new k("installFloatingLayerPostion", 0);
    public static k bxM = new k("remindInstallStyle", 0);
    public static k bxN = new k("remindInstallTime", 60);
    public static k bxO = new k("watermarkKwaiIdSwitch", 0);
    public static k aLt = new k("insertScreenV2Switch", 0);
    public static k bxP = new k("insertScreenAutoPlaySwitch", 0);
    public static j bxQ = new j("insertScreenV2ShowConfig");
    public static k bxR = new k("environmentDetectEnable", 0);
    public static k bxS = new k("simCardInfoEnable", 0);
    public static k bxT = new k("baseStationEnable", 0);
    public static k bxU = new k("sensorEventEnable2", 0);
    public static k bxV = new k("lpAutoDownloadApkSwitch", 1);
    public static k bxW = new k("autoDownloadUrlSwitch", 0);
    public static k bxX = new k("insertScreenAdType", 0);
    public static k bxY = new k("interstitialAutoCallAppCountDaily", 1);
    public static k bxZ = new k("mediaControlPlaySwitch", 1);
    public static r bya = new r("appStatusSoUrlV7a", "");
    public static r byb = new r("appStatusSoUrlV8a", "");
    public static r byc = new r("appStatusSoVersion", "");
    public static k byd = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d bye = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h byf = new h();
    public static com.kwad.sdk.core.config.item.d byg = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d byh = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static r byi = new r("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d byj = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d byk = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d byl = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d bym = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k byn = new k("forceActivate", 0);
    public static k byo = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d byp = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static r byq = new r("nativeAndAnrDynamic", "");
    public static k byr = new k("kwaiAppVersionSwitch", 1);
    public static com.kwad.sdk.core.config.item.d bys = new com.kwad.sdk.core.config.item.d("disableLogcatOAID", false);
    public static r byt = new r("userAgent");
    public static k byu = new k("biddingLogSwitch", 0);
    public static k byv = new k("forceActiveThreshold", 5);
    public static k byw = new k("forceActiveInterval", 3);
    public static k byx = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d byy = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g byz = new g("adExposureAreaPercent", 0.3f);
    public static g byA = new g("adExposureTime", -1.0f);
    public static g byB = new g("drawAdExposureAreaPercent", 0.7f);
    public static g byC = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d byD = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d byE = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k byF = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d byG = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d byH = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static k byI = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d byJ = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d byK = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static o byL = new o("obiwanLogFilesDiskQuota", Long.valueOf(Config.RAVEN_LOG_LIMIT));
    public static m byM = new m("logCommandResult", "", false);
    public static o byN = new o("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d byO = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static k byP = new k("playableAutoPlayEnable", 1);
    public static k byQ = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d byR = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d byS = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k byT = new k("weaponSwitch", 1);
    public static k byU = new k("kvModeV2", 0);
    public static i byV = new i();
    public static k byW = new k("idcRollbackInterval", 0);
    public static o byX = new o("currentServerTimeMs");
    public static k byY = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g byZ = new g("adTraceReportRate", 1.0f);
    public static k bza = new k("adTraceRepeatEnable", 0);
    public static k bzb = new k("appHeartBeatInterval", 0);
    public static k bzc = new k("insertShowPercent", 100);
    public static k bzd = new k("adCacheCode", 0);
    public static r bze = new r("installTipsContentDesc", "");
    public static r bzf = new r("installTipsPositiveActionDesc", "");
    public static r bzg = new r("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d bzh = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static com.kwad.sdk.core.config.item.d bzi = new com.kwad.sdk.core.config.item.d("resourceWarmupSwitch", false);
    public static k bzj = new k("resourceWarmupDelayTime", 5);
    public static r bzk = new r("perfMonitorV2", "");
    public static k bzl = new k("neoVideoAdaptStrategy", 1);
    public static k bzm = new k("feedTKLoadTimeOut", 2500);
    public static k bzn = new k("drawTKLoadTimeOut", 2000);
    public static com.kwad.sdk.core.config.item.d bzo = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static k bzp = new k("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d bzq = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static k bzr = new k("videoCacheOpt", 0);
    public static r bzs = new r("ranger", "");
    public static k bzt = new k("hdrConfig", 0);
    public static r bzu = new r("packageInstall", "");
    public static r bzv = new r("eplV1", "");
    public static r bzw = new r("threadPoolPerfMonitor", "");
    public static r bzx = new r("threadPoolParams", "");
    public static f bzy = new f("crashUploadRate", Double.valueOf(1.0d));
    public static f bzz = new f("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d bzA = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d bzB = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d bzC = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d bzD = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d bzE = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d bzF = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d bzG = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static k bzH = new k("tubeRenderType", 0);
    public static k bzI = new k("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d bzJ = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d bzK = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static r bzL = new r("trackBlackUrlConfig", "");
    public static k bzM = new k("tkMemCacheSize", 0);
    public static s bzN = new s("preloadMemCacheTemplateIds", new ArrayList(0));
    public static k bzO = new k("kGeoInfoConfig", 1);
    public static k bzP = new k("appMonitorSwitch", 0);
    public static k bzQ = new k("videoCacheErrorCallbackSwitch", 0);
    public static k bzR = new k("tkErrorDetailCount", 1);
    public static k bzS = new k("videoLaunchOptimiseSwitch", 0);
    public static k bzT = new k("enableInitStartMode", 1);
    public static r bzU = new r("localLogConfig", "");
    public static r bzV = new r("adLogRetryConfig", "");
    public static n bzW = new n("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d bzX = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static k bzY = new k("adRequestNum", 1);
    public static k bzZ = new k("carouselInterval", 30000);
    public static o bAa = new o("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d bAb = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static k bAc = new k("optimizeProgressMethod", 0);
    public static k bAd = new k("splashLoadTimeOptimize", 0);
    public static o bAe = new o("splashVisibleCheckDelayTime", 500L);
    public static com.kwad.sdk.core.config.item.d bAf = new com.kwad.sdk.core.config.item.d("isWaynePlayerValid", false);
    public static com.kwad.sdk.core.config.item.d bAg = new com.kwad.sdk.core.config.item.d("isWaynePlayerAsDefaultPlayer", false);
    public static m bAh = new m("waynePlayerPlayConfig", null);
    public static k bAi = new k("waynePlayerSupportAndroidApi", 24);
    public static com.kwad.sdk.core.config.item.d bAj = new com.kwad.sdk.core.config.item.d("enableThreadOpt2", false);
    public static m bAk = new m("cheatInfoConfig", null);
    public static m bAl = new m("featureCollectConfig", null);
    public static final k bAm = new k("installerCheckPkgAbSwitch", 0);
    public static final r bAn = new r("installerCheckExtraPkgs", "");
    public static final k bAo = new k("probeBatch", 0);

    public static void init() {
    }
}
